name: frontend
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.3
  geolocator: ^9.0.0
  google_maps_flutter: ^2.2.3  
  shared_preferences: ^2.0.6
  sensors_plus: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
